const form=document.getElementById('newTermForm'),yearInput=document.getElementById('academicYear'),semesterInput=document.getElementById('semester'),startDate=document.getElementById('startDate'),endDate=document.getElementById('endDate'),copySchedule=document.getElementById('copySchedule'),button=document.getElementById('createButton'),list=document.getElementById('termList'),message=document.getElementById('message'),nextTermHint=document.getElementById('nextTermHint');
function msg(text,error=false){message.textContent=text;message.classList.remove('hidden');message.style.background=error?'#fee2e2':'#dcfce7';message.style.color=error?'#991b1b':'#166534';}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));}
function thaiDate(v){if(!v)return '-';const d=new Date(v+'T00:00:00');return d.toLocaleDateString('th-TH',{dateStyle:'medium'});}
function nextTermFrom(term){if(!term)return null;const sem=Number(term.semester);return sem>=3?{year:Number(term.academic_year)+1,semester:1}:{year:Number(term.academic_year),semester:sem+1};}
function setSuggestedTerm(term){const next=nextTermFrom(term);if(!next)return;yearInput.value=next.year;semesterInput.value=String(next.semester);nextTermHint.textContent=`แนะนำ: ภาคเรียนถัดจาก ${term.name} คือ ${next.year}/${next.semester}`;}
async function load(){const {data:term,error:termError}=await supabaseClient.from('academic_terms').select('*').order('academic_year',{ascending:false}).order('semester',{ascending:false});if(termError){msg('โหลดภาคเรียนไม่ได้: '+termError.message,true);return;}const rows=term||[];const active=rows.find(t=>t.active);if(active&&!form.dataset.userEdited)setSuggestedTerm(active);list.innerHTML=rows.length?rows.map(t=>`<article class="term-card ${t.active?'current':''}"><h2>${esc(t.name)}</h2><div class="term-meta">ปีการศึกษา ${esc(t.academic_year)} • ภาคเรียน ${esc(t.semester)}</div><div class="term-meta">ช่วงภาคเรียน: <strong>${thaiDate(t.start_date)} – ${thaiDate(t.end_date)}</strong></div><div class="term-actions">${t.active?'<strong>🟢 ภาคเรียนปัจจุบัน</strong>':`<button class="small-button" onclick="activateTerm('${t.id}')">ใช้ภาคเรียนนี้</button>`}<button class="small-button" onclick="editDates('${t.id}','${t.start_date||''}','${t.end_date||''}')">📅 กำหนดวันเปิด–ปิด</button></div></article>`).join(''):'<div class="empty-state">ยังไม่มีข้อมูลภาคเรียน</div>';}
window.activateTerm=async function(id){if(!confirm('เปลี่ยนภาคเรียนปัจจุบันหรือไม่? หน้าตารางเรียนใหม่จะอ้างอิงภาคเรียนนี้'))return;const {data,error}=await supabaseClient.rpc('set_active_academic_term',{p_term_id:id});if(error){msg('เปลี่ยนภาคเรียนไม่ได้: '+error.message,true);return;}msg('เปิดใช้งานภาคเรียน '+(data?.name||'สำเร็จ'));form.dataset.userEdited='';await load();};
window.editDates=async function(id,start,end){const newStart=prompt('วันเริ่มภาคเรียน (YYYY-MM-DD)',start||'');if(newStart===null)return;const newEnd=prompt('วันสิ้นสุดภาคเรียน (YYYY-MM-DD)',end||'');if(newEnd===null)return;if(newStart&&newEnd&&newStart>newEnd){msg('วันเริ่มภาคเรียนต้องไม่เกินวันสิ้นสุด',true);return;}const {error}=await supabaseClient.rpc('update_academic_term_dates',{p_term_id:id,p_start_date:newStart||null,p_end_date:newEnd||null});if(error){msg('กำหนดวันเปิด–ปิดไม่ได้: '+error.message,true);return;}msg('บันทึกวันเปิด–ปิดภาคเรียนแล้ว');await load();};
form.addEventListener('input',()=>{form.dataset.userEdited='1';});
form.addEventListener('submit',async e=>{e.preventDefault();const year=Number(yearInput.value),semester=Number(semesterInput.value);if(year<2500||year>3000){msg('กรุณาระบุปีการศึกษาให้ถูกต้อง',true);return;}if(startDate.value&&endDate.value&&startDate.value>endDate.value){msg('วันเริ่มภาคเรียนต้องไม่เกินวันสิ้นสุด',true);return;}button.disabled=true;try{const {data,error}=await supabaseClient.rpc('create_next_academic_term',{p_academic_year:year,p_semester:semester,p_start_date:startDate.value||null,p_end_date:endDate.value||null,p_copy_schedule_from_active:copySchedule.checked});if(error)throw error;msg(`สร้างภาคเรียน ${year}/${semester} แล้ว`);form.dataset.userEdited='';form.reset();copySchedule.checked=true;const next=nextTermFrom({academic_year:year,semester});if(next){yearInput.value=next.year;semesterInput.value=String(next.semester);nextTermHint.textContent=`แนะนำ: ภาคเรียนถัดไปคือ ${next.year}/${next.semester}`;}await load();}catch(e){msg('สร้างภาคเรียนไม่ได้: '+e.message,true);}finally{button.disabled=false;}});
load();