const params=new URLSearchParams(location.search),sessionId=params.get('session');
const info=document.getElementById('sessionInfo'),form=document.getElementById('attendanceForm'),codeInput=document.getElementById('studentCode'),button=document.getElementById('confirmButton'),message=document.getElementById('message'),confirmation=document.getElementById('confirmation'),registerCard=document.getElementById('registerCard'),registerForm=document.getElementById('registerForm'),registerButton=document.getElementById('registerButton'),registerPrefix=document.getElementById('registerPrefix'),registerFirstName=document.getElementById('registerFirstName'),registerLastName=document.getElementById('registerLastName'),registerHint=document.getElementById('registerHint');
let session=null,subject=null,activeTerm=null,pendingStudent=null;
const CHECKIN_EARLY_MINUTES=15;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function show(t,error=false){message.textContent=t;message.classList.remove('hidden');message.style.background=error?'#fee2e2':'#dcfce7';message.style.color=error?'#991b1b':'#166534';}
function hideMessage(){message.classList.add('hidden');}
function formatCheckedAt(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('th-TH',{dateStyle:'short',timeStyle:'medium'});}
function timeToMinutes(v){if(!v)return null;const m=String(v).match(/^(\d{1,2}):(\d{2})/);if(!m)return null;return Number(m[1])*60+Number(m[2]);}
function checkinWindow(){const start=timeToMinutes(session?.start_time),end=timeToMinutes(session?.end_time);if(start===null||end===null)return {ok:true};const now=new Date(),current=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;return {ok:current>=start-CHECKIN_EARLY_MINUTES&&current<=end,start,end,current};}
function windowMessage(){const w=checkinWindow();if(w.ok)return '';const start=Math.max(0,w.start-CHECKIN_EARLY_MINUTES),end=w.end,fmt=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;return w.current<start?`⏳ ยังไม่ถึงเวลาเช็กชื่อ\nระบบจะเปิดรับตั้งแต่ ${fmt(start)} น.`:`⏰ หมดเวลาเช็กชื่อแล้ว\nระบบปิดรับเวลา ${fmt(end)} น.`;}
function studentName(s){return [s?.prefix,s?.first_name,s?.last_name].filter(Boolean).join(' ');}
function showConfirmation(student,afterRegistration=false){pendingStudent=student;form.classList.add('hidden');registerCard.classList.add('hidden');hideMessage();confirmation.innerHTML=`<h2 id="confirmationTitle">🔎 ยืนยันข้อมูล</h2><p class="confirmation-name">${esc(studentName(student))}</p><p class="confirmation-detail">รหัสนักเรียน: ${esc(student.student_id)}</p><p class="confirmation-detail">ห้อง: ${esc(student.class_name)}</p>${afterRegistration?'<p class="confirmation-detail">🆕 ลงทะเบียนรายวิชาเรียบร้อยแล้ว</p>':''}<div class="confirmation-actions"><button type="button" class="confirm-identity" id="confirmIdentity">✅ ข้อมูลถูกต้อง</button><button type="button" class="cancel-identity" id="cancelIdentity">↩️ กลับไปแก้ไข</button></div>`;confirmation.classList.remove('hidden');document.getElementById('confirmIdentity').addEventListener('click',recordPending);document.getElementById('cancelIdentity').addEventListener('click',()=>{confirmation.classList.add('hidden');form.classList.remove('hidden');codeInput.focus();});}
async function recordPending(){if(!pendingStudent||!session)return;const w=checkinWindow();if(!w.ok){show(windowMessage(),true);confirmation.classList.add('hidden');form.classList.remove('hidden');return;}const name=studentName(pendingStudent);const {data:existing,error:existingError}=await supabaseClient.from('attendance_records').select('id,status,checked_at').eq('session_id',session.id).eq('student_id',pendingStudent.id).maybeSingle();if(existingError){show('❌ ตรวจสอบข้อมูลไม่สำเร็จ\n'+existingError.message,true);return;}if(existing){const previousTime=formatCheckedAt(existing.checked_at);confirmation.classList.add('hidden');show(`⚠️ เช็กชื่อแล้ว\n${name}\nสถานะ: ${existing.status||'present'}${previousTime?`\nเวลาเช็กชื่อ: ${previousTime}`:''}\n\nระบบจะไม่บันทึกซ้ำ`,true);return;}const {error:insertError}=await supabaseClient.from('attendance_records').insert({session_id:session.id,student_id:pendingStudent.id,status:'present'});if(insertError){if(insertError.code==='23505'){show(`⚠️ เช็กชื่อแล้ว\n${name}\nระบบป้องกันการบันทึกซ้ำให้โดยอัตโนมัติ`,true);confirmation.classList.add('hidden');return;}show('❌ เช็กชื่อไม่สำเร็จ\n'+insertError.message,true);return;}confirmation.classList.add('hidden');show(`✅ เช็กชื่อสำเร็จ\n\n${name}\nรหัสนักเรียน: ${pendingStudent.student_id}\nสถานะ: มาเรียน\nเวลา: ${new Date().toLocaleTimeString('th-TH')}`);pendingStudent=null;}
function showRegistration(){form.classList.add('hidden');confirmation.classList.add('hidden');registerCard.classList.remove('hidden');const cap=subject?.max_students;registerHint.textContent=cap?`รายวิชานี้เปิดรับลงทะเบียน • จำนวนรับสูงสุด ${cap} คน`:'รายวิชานี้เปิดรับลงทะเบียน • ไม่จำกัดจำนวน';registerFirstName.focus();}
async function registerExistingStudent(student){if(!subject?.registration_open){show('❌ นักเรียนยังไม่ได้ลงทะเบียนรายวิชานี้',true);return;}if(!activeTerm){show('❌ ไม่พบภาคเรียนปัจจุบัน',true);return;}show(`📝 พบข้อมูล ${studentName(student)}\nกำลังลงทะเบียนรายวิชาให้โดยอัตโนมัติ...`);const {data,error}=await supabaseClient.rpc('register_student_for_session',{p_session_id:session.id,p_student_id:student.student_id,p_prefix:student.prefix||'',p_first_name:student.first_name||'',p_last_name:student.last_name||''});if(error){show('❌ ลงทะเบียนรายวิชาไม่สำเร็จ\n'+error.message,true);return;}const registered={id:data?.student_id||student.id,student_id:data?.student_code||student.student_id,prefix:data?.prefix??student.prefix,first_name:data?.first_name??student.first_name,last_name:data?.last_name??student.last_name,class_name:data?.class_name??student.class_name};showConfirmation(registered,true);}
async function load(){if(!sessionId){info.textContent='ไม่พบรหัสคาบเรียน';form.classList.add('hidden');return;}const {data,error}=await supabaseClient.from('attendance_sessions').select('*').eq('id',sessionId).single();if(error){info.textContent='โหลดคาบเรียนไม่สำเร็จ: '+error.message;form.classList.add('hidden');return;}session=data;const termResult=await supabaseClient.from('academic_terms').select('id,name').eq('active',true).maybeSingle();if(termResult.error){info.textContent='โหลดภาคเรียนไม่สำเร็จ: '+termResult.error.message;form.classList.add('hidden');return;}activeTerm=termResult.data;if(!activeTerm||session.term_id!==activeTerm.id){info.textContent='คาบเรียนนี้ไม่อยู่ในภาคเรียนปัจจุบัน';form.classList.add('hidden');return;}const subjectResult=await supabaseClient.from('attendance_subjects').select('id,subject_code,subject_name,active,max_students,registration_open').eq('subject_code',session.subject_code).maybeSingle();if(subjectResult.error){info.textContent='โหลดรายวิชาไม่สำเร็จ: '+subjectResult.error.message;form.classList.add('hidden');return;}subject=subjectResult.data||null;info.innerHTML=`<strong>${esc(session.subject_name)}</strong><br>${esc(session.subject_code)} • 👥 ${esc(session.class_name)}<br>📅 ${esc(session.session_date)} • ⏰ ${esc(session.start_time)}–${esc(session.end_time)}<br>🕐 เปิดเช็กชื่อก่อนเวลา ${CHECKIN_EARLY_MINUTES} นาที`;if(session.status!=='open'){show('คาบเรียนนี้ปิดการเช็กชื่อแล้ว',true);form.classList.add('hidden');return;}const msg=windowMessage();if(msg)show(msg,true);}
form.addEventListener('submit',async e=>{e.preventDefault();const code=codeInput.value.trim();if(!session||session.status!=='open'||!code)return;const w=checkinWindow();if(!w.ok){show(windowMessage(),true);return;}button.disabled=true;hideMessage();try{const {data:student,error:studentError}=await supabaseClient.from('attendance_students').select('id,student_id,prefix,first_name,last_name,class_name,status').eq('student_id',code).maybeSingle();if(studentError)throw studentError;if(!student){if(subject?.registration_open){showRegistration();return;}show('❌ ไม่พบรหัสนักเรียนนี้\nรายวิชานี้ยังไม่ได้เปิดรับลงทะเบียน',true);return;}if(student.status!=='active'){show('❌ ไม่สามารถเช็กชื่อได้\nนักเรียนคนนี้ไม่ได้อยู่ในสถานะ active',true);return;}if(student.class_name!==session.class_name){show(`❌ ไม่สามารถเช็กชื่อได้\nห้องไม่ตรงกัน: ${student.class_name} / คาบ ${session.class_name}`,true);return;}if(!activeTerm){show('❌ ไม่พบภาคเรียนปัจจุบัน',true);return;}const {data:enrollment,error:enrollmentError}=await supabaseClient.from('attendance_subject_enrollments').select('id').eq('term_id',activeTerm.id).eq('subject_id',subject?.id||'00000000-0000-0000-0000-000000000000').eq('student_id',student.id).eq('status','active').maybeSingle();if(enrollmentError)throw enrollmentError;if(!enrollment){if(subject?.registration_open){await registerExistingStudent(student);return;}show('❌ นักเรียนยังไม่ได้ลงทะเบียนรายวิชานี้',true);return;}showConfirmation(student,false);}catch(e){show('❌ ตรวจสอบไม่สำเร็จ\n'+e.message,true);}finally{button.disabled=false;}});
registerForm.addEventListener('submit',async e=>{e.preventDefault();const code=codeInput.value.trim(),first=registerFirstName.value.trim(),last=registerLastName.value.trim(),prefix=registerPrefix.value.trim();if(!code||!first||!last)return;registerButton.disabled=true;try{const {data,error}=await supabaseClient.rpc('register_student_for_session',{p_session_id:session.id,p_student_id:code,p_prefix:prefix,p_first_name:first,p_last_name:last});if(error)throw error;const student={id:data.student_id,student_id:data.student_code,prefix:data.prefix,first_name:data.first_name,last_name:data.last_name,class_name:data.class_name};showConfirmation(student,true);}catch(e){show('❌ ลงทะเบียนไม่สำเร็จ\n'+e.message,true);}finally{registerButton.disabled=false;}});
load();