const sessionSelect=document.getElementById('sessionSelect');
const sessionInfo=document.getElementById('sessionInfo');
const codeInput=document.getElementById('studentCode');
const button=document.getElementById('checkinButton');
const result=document.getElementById('result');
const recordList=document.getElementById('recordList');
const connection=document.getElementById('connectionStatus');
let sessions=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function show(t,err=false){result.textContent=t;result.classList.remove('hidden');result.style.background=err?'#fee2e2':'#dcfce7';result.style.color=err?'#991b1b':'#166534';}
async function loadSessions(){const {data,error}=await supabaseClient.from('attendance_sessions').select('*').eq('status','open').order('session_date',{ascending:false}).order('created_at',{ascending:false});if(error){connection.textContent='❌ เชื่อมต่อไม่ได้: '+error.message;connection.style.background='#fee2e2';connection.style.color='#991b1b';return;}connection.textContent='🟢 เชื่อมต่อฐานข้อมูลสำเร็จ';sessions=data||[];sessionSelect.innerHTML='<option value="">— เลือกคาบเรียน —</option>'+sessions.map(s=>`<option value="${s.id}">${esc(s.subject_name)} • ${esc(s.class_name)} • ${esc(s.session_date)}</option>`).join('');}
async function loadRecords(){const s=sessions.find(x=>x.id===sessionSelect.value);if(!s){sessionInfo.classList.add('hidden');recordList.textContent='เลือกคาบเรียนก่อน';return;}sessionInfo.classList.remove('hidden');sessionInfo.innerHTML=`<div><span>วิชา</span><strong>${esc(s.subject_name)}</strong></div><div><span>ห้อง</span><strong>${esc(s.class_name)}</strong></div><div><span>วันที่</span><strong>${esc(s.session_date)}</strong></div>`;const {data,error}=await supabaseClient.from('attendance_records').select('checked_at,status,attendance_students(student_id,first_name,last_name,prefix)').eq('session_id',s.id).order('checked_at',{ascending:false});if(error){recordList.textContent='โหลดประวัติไม่ได้: '+error.message;return;}recordList.innerHTML=data?.length?data.map(r=>`<div class="history-item">🟢 <strong>${esc([r.attendance_students?.prefix,r.attendance_students?.first_name,r.attendance_students?.last_name].filter(Boolean).join(' '))}</strong> • ${esc(r.attendance_students?.student_id)}<br><span>${new Date(r.checked_at).toLocaleString('th-TH')}</span></div>`).join(''):'ยังไม่มีผู้เช็กชื่อ';}
sessionSelect.addEventListener('change',loadRecords);
button.addEventListener('click',async()=>{const session=sessions.find(x=>x.id===sessionSelect.value);const code=codeInput.value.trim();if(!session){show('กรุณาเลือกคาบเรียนก่อน',true);return;}if(!code){show('กรุณาใส่รหัสนักเรียน',true);return;}button.disabled=true;try{const {data:student,error:studentError}=await supabaseClient.from('attendance_students').select('id,student_id,prefix,first_name,last_name,class_name,status').eq('student_id',code).maybeSingle();if(studentError)throw studentError;if(!student){show('ไม่พบรหัสนักเรียนนี้',true);return;}if(student.status!=='active'){show('นักเรียนคนนี้ไม่ได้อยู่ในสถานะ active',true);return;}if(student.class_name!==session.class_name){show(`นักเรียนอยู่ห้อง ${student.class_name} ไม่ตรงกับคาบ ${session.class_name}`,true);return;}const {error}=await supabaseClient.from('attendance_records').insert({session_id:session.id,student_id:student.id,status:'present'});if(error){if(error.code==='23505')show(`⚠️ ${[student.prefix,student.first_name,student.last_name].filter(Boolean).join(' ')} เช็กชื่อไปแล้ว`,true);else throw error;return;}show(`✅ เช็กชื่อสำเร็จ: ${[student.prefix,student.first_name,student.last_name].filter(Boolean).join(' ')}`);codeInput.value='';await loadRecords();}catch(e){show('เช็กชื่อไม่สำเร็จ: '+e.message,true);}finally{button.disabled=false;}});
loadSessions();
