const termSelect=document.getElementById('termSelect'),subjectSelect=document.getElementById('subjectSelect'),classSelect=document.getElementById('classSelect'),search=document.getElementById('studentSearch'),table=document.getElementById('studentTable'),empty=document.getElementById('emptyState'),capacity=document.getElementById('capacity'),connection=document.getElementById('connectionStatus'),message=document.getElementById('message'),checkAll=document.getElementById('checkAll'),selectAll=document.getElementById('selectAll'),selectionCount=document.getElementById('selectionCount'),enrollButton=document.getElementById('enrollButton'),removeButton=document.getElementById('removeButton');
let terms=[],subjects=[],students=[],enrolledIds=new Set(),activeTerm=null;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function fullName(s){return [s.prefix,s.first_name,s.last_name].filter(Boolean).join(' ');}
function show(text,error=false){message.textContent=text;message.classList.remove('hidden');message.style.background=error?'#fee2e2':'#dcfce7';message.style.color=error?'#991b1b':'#166534';}
function selectedIds(){return [...table.querySelectorAll('input.student-check:checked')].map(x=>x.value);}
function updateSelection(){const ids=selectedIds();selectionCount.textContent=`เลือก ${ids.length} คน`;enrollButton.disabled=ids.length===0||!termSelect.value||!subjectSelect.value||!classSelect.value;removeButton.disabled=ids.length===0||!termSelect.value||!subjectSelect.value||!classSelect.value;const boxes=[...table.querySelectorAll('input.student-check')];checkAll.disabled=boxes.length===0;checkAll.checked=boxes.length>0&&boxes.every(x=>x.checked);}
async function loadTerms(){const {data,error}=await supabaseClient.from('academic_terms').select('id,name,academic_year,semester,active').order('academic_year',{ascending:false}).order('semester',{ascending:false});if(error)throw error;terms=data||[];activeTerm=terms.find(x=>x.active)||null;termSelect.innerHTML=terms.map(t=>`<option value="${t.id}">${esc(t.name)}${t.active?' • ปัจจุบัน':''}</option>`).join('');if(activeTerm)termSelect.value=activeTerm.id;}
async function loadSubjects(){const {data,error}=await supabaseClient.from('attendance_subjects').select('id,subject_code,subject_name,max_students,active').eq('active',true).order('subject_code');if(error)throw error;subjects=data||[];subjectSelect.innerHTML='<option value="">-- เลือกรายวิชา --</option>'+subjects.map(s=>`<option value="${s.id}">${esc(s.subject_code)} • ${esc(s.subject_name)}</option>`).join('');}
async function loadClasses(){const {data,error}=await supabaseClient.from('attendance_students').select('class_name').eq('status','active').not('class_name','is',null);if(error)throw error;const classes=[...new Set((data||[]).map(x=>String(x.class_name).trim()).filter(Boolean))].sort();classSelect.innerHTML='<option value="">-- เลือกห้อง --</option>'+classes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');}
async function loadStudents(){const classroom=classSelect.value,subjectId=subjectSelect.value,termId=termSelect.value;if(!classroom||!subjectId||!termId){students=[];enrolledIds=new Set();render();return;}const [sr,er]=await Promise.all([supabaseClient.from('attendance_students').select('id,student_id,student_no,prefix,first_name,last_name,class_name,status').eq('class_name',classroom).eq('status','active').order('student_no',{ascending:true,nullsFirst:false}).order('student_id'),supabaseClient.from('attendance_subject_enrollments').select('student_id').eq('term_id',termId).eq('subject_id',subjectId).eq('class_name',classroom).eq('status','active')]);if(sr.error)throw sr.error;if(er.error)throw er.error;students=sr.data||[];enrolledIds=new Set((er.data||[]).map(x=>x.student_id));render();}
function render(){const q=search.value.trim().toLowerCase(),rows=students.filter(s=>[s.student_id,fullName(s),s.class_name].some(v=>String(v??'').toLowerCase().includes(q)));table.innerHTML=rows.map((s,i)=>{const enrolled=enrolledIds.has(s.id);return `<tr class="${enrolled?'row-enrolled':''}"><td><input class="student-check" type="checkbox" value="${s.id}"></td><td>${i+1}</td><td><strong>${esc(s.student_id)}</strong></td><td>${esc(fullName(s))}</td><td>${esc(s.class_name)}</td><td class="${enrolled?'status-enrolled':'status-not'}">${enrolled?'✅ ลงทะเบียนแล้ว':'— ยังไม่ลงทะเบียน'}</td></tr>`;}).join('');empty.classList.toggle('hidden',rows.length>0);updateSelection();updateCapacity();}
function updateCapacity(){const s=subjects.find(x=>x.id===subjectSelect.value);const n=enrolledIds.size;if(!s){capacity.textContent='ยังไม่ได้เลือก';return;}capacity.textContent=s.max_students?`ลงทะเบียน ${n}/${s.max_students} คน`:`ลงทะเบียน ${n} คน • ไม่จำกัด`;capacity.style.background=s.max_students&&n>=s.max_students?'#fee2e2':'#fef2f2';}
async function manage(action){const ids=selectedIds();if(!ids.length)return;const term=terms.find(x=>x.id===termSelect.value),subject=subjects.find(x=>x.id===subjectSelect.value),classroom=classSelect.value;if(!term||!subject||!classroom)return;const verb=action==='enroll'?'ลงทะเบียน':'ถอนการลงทะเบียน';if(!confirm(`${verb}นักเรียน ${ids.length} คน\nรายวิชา ${subject.subject_code}\nห้อง ${classroom}\nภาคเรียน ${term.name}\n\nยืนยันหรือไม่?`))return;enrollButton.disabled=true;removeButton.disabled=true;try{const {data,error}=await supabaseClient.rpc('manage_subject_enrollments',{p_term_id:term.id,p_subject_id:subject.id,p_class_name:classroom,p_student_ids:ids,p_action:action});if(error)throw error;show(action==='enroll'?`✅ ลงทะเบียนสำเร็จ ${data?.enrolled||0} คน • ข้าม ${data?.skipped||0} คน`:`↩️ ถอนการลงทะเบียนสำเร็จ ${data?.removed||0} คน`);await loadStudents();}catch(e){show(`❌ ${verb}ไม่สำเร็จ\n${e.message}`,true);}finally{updateSelection();}}
termSelect.addEventListener('change',async()=>{try{search.value='';await loadStudents();}catch(e){show('โหลดข้อมูลไม่ได้: '+e.message,true);}});subjectSelect.addEventListener('change',async()=>{try{search.value='';await loadStudents();}catch(e){show('โหลดข้อมูลไม่ได้: '+e.message,true);}});classSelect.addEventListener('change',async()=>{try{search.value='';await loadStudents();}catch(e){show('โหลดข้อมูลไม่ได้: '+e.message,true);}});search.addEventListener('input',render);checkAll.addEventListener('change',()=>{table.querySelectorAll('input.student-check').forEach(x=>x.checked=checkAll.checked);updateSelection();});selectAll.addEventListener('click',()=>{table.querySelectorAll('input.student-check').forEach(x=>x.checked=true);updateSelection();});table.addEventListener('change',e=>{if(e.target.classList.contains('student-check'))updateSelection();});enrollButton.addEventListener('click',()=>manage('enroll'));removeButton.addEventListener('click',()=>manage('remove'));
(async function(){try{await loadTerms();await loadSubjects();await loadClasses();connection.textContent=`🟢 เชื่อมต่อฐานข้อมูลสำเร็จ • ภาคเรียน ${activeTerm?.name||'ยังไม่ได้ตั้ง'}`;if(!activeTerm){show('กรุณาตั้งภาคเรียนปัจจุบันก่อนลงทะเบียนเรียน',true);return;}await loadStudents();}catch(e){connection.textContent='❌ โหลดข้อมูลไม่ได้: '+e.message;connection.style.background='#fee2e2';connection.style.color='#991b1b';}})();