const sessionSelect=document.getElementById('sessionSelect');
const result=document.getElementById('scanResult');
const connection=document.getElementById('connectionStatus');
let sessions=[]; let lastScan=''; let lastScanAt=0;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function show(t,err=false){result.textContent=t;result.classList.remove('hidden');result.style.background=err?'#fee2e2':'#dcfce7';result.style.color=err?'#991b1b':'#166534';}
async function loadSessions(){const {data,error}=await supabaseClient.from('attendance_sessions').select('*').eq('status','open').order('session_date',{ascending:false}).order('created_at',{ascending:false});if(error){connection.textContent='❌ เชื่อมต่อไม่ได้: '+error.message;connection.style.background='#fee2e2';connection.style.color='#991b1b';return;}connection.textContent='🟢 เชื่อมต่อฐานข้อมูลสำเร็จ';sessions=data||[];sessionSelect.innerHTML='<option value="">— เลือกคาบเรียน —</option>'+sessions.map(s=>`<option value="${s.id}">${esc(s.subject_name)} • ${esc(s.class_name)} • ${esc(s.session_date)}</option>`).join('');}
async function checkin(decodedText){const session=sessions.find(s=>s.id===sessionSelect.value);if(!session){show('กรุณาเลือกคาบเรียนก่อน',true);return;}const code=decodedText.trim().replace(/^student:/i,'');if(!code){show('QR นี้ไม่มีรหัสนักเรียน',true);return;}if(code===lastScan && Date.now()-lastScanAt<2500)return;lastScan=code;lastScanAt=Date.now();const {data:student,error:studentError}=await supabaseClient.from('attendance_students').select('id,student_id,prefix,first_name,last_name,class_name,status').eq('student_id',code).maybeSingle();if(studentError){show('ค้นหานักเรียนไม่สำเร็จ: '+studentError.message,true);return;}if(!student){show('❌ ไม่พบรหัสนักเรียน '+code,true);return;}if(student.status!=='active'){show('❌ นักเรียนคนนี้ไม่ได้อยู่ในสถานะ active',true);return;}if(student.class_name!==session.class_name){show(`❌ ห้องไม่ตรงกัน: นักเรียน ${student.class_name} / คาบ ${session.class_name}`,true);return;}const {error}=await supabaseClient.from('attendance_records').insert({session_id:session.id,student_id:student.id,status:'present'});if(error){if(error.code==='23505')show(`⚠️ ${[student.prefix,student.first_name,student.last_name].filter(Boolean).join(' ')} เช็กชื่อไปแล้ว`,true);else show('บันทึกไม่สำเร็จ: '+error.message,true);return;}show(`✅ เช็กชื่อสำเร็จ: ${[student.prefix,student.first_name,student.last_name].filter(Boolean).join(' ')} • ${new Date().toLocaleTimeString('th-TH')}`);}
const scanner=new Html5QrcodeScanner('reader',{fps:10,qrbox:{width:250,height:250},rememberLastUsedCamera:true},false);scanner.render(checkin,(errorMessage)=>{});loadSessions();
