const form=document.getElementById('sessionForm'),table=document.getElementById('sessionTable'),search=document.getElementById('searchSession'),count=document.getElementById('sessionCount'),empty=document.getElementById('emptyState'),message=document.getElementById('message');
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function msg(t,err=false){message.textContent=t;message.classList.remove('hidden');message.style.background=err?'#fee2e2':'#dcfce7';message.style.color=err?'#991b1b':'#166534';}
function code(date){return `AT-${date.replaceAll('-','')}-${String(Date.now()).slice(-6)}`;}
async function load(){const {data,error}=await supabaseClient.from('attendance_sessions').select('*').order('session_date',{ascending:false}).order('created_at',{ascending:false});if(error){msg('โหลดคาบเรียนไม่สำเร็จ: '+error.message,true);return;}sessions=data||[];render();}
let sessions=[];
function render(){const k=search.value.trim().toLowerCase(),rows=sessions.filter(s=>[s.session_code,s.subject_code,s.subject_name,s.class_name].some(v=>String(v??'').toLowerCase().includes(k)));count.textContent=`${sessions.length} คาบ`;empty.classList.toggle('hidden',rows.length>0);table.innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.session_code)}</strong></td><td>${esc(s.subject_code||'')}<br>${esc(s.subject_name)}</td><td>${esc(s.class_name)}</td><td>${esc(s.session_date)}</td><td>${esc(s.start_time||'-')} – ${esc(s.end_time||'-')}</td><td>${s.status==='open'?'🟢 เปิด':'⚫ ปิด'}</td><td class="actions">${s.status==='open'?`<button class="small-button" onclick="closeSession('${encodeURIComponent(s.id)}')">ปิดคาบ</button>`:`<span>—</span>`}</td></tr>`).join('');}
form.addEventListener('submit',async e=>{e.preventDefault();const subjectCode=document.getElementById('subjectCode').value.trim()||null,subjectName=document.getElementById('subjectName').value.trim(),className=document.getElementById('className').value.trim(),sessionDate=document.getElementById('sessionDate').value,startTime=document.getElementById('startTime').value||null,endTime=document.getElementById('endTime').value||null;if(!subjectName||!className||!sessionDate)return;if(startTime&&endTime&&startTime>=endTime){msg('เวลาเริ่มต้องน้อยกว่าเวลาสิ้นสุด',true);return;}const duplicate=(sessions||[]).find(s=>s.session_date===sessionDate&&s.subject_code===subjectCode&&s.class_name===className&&s.start_time===startTime&&s.status==='open');if(duplicate){msg('คาบนี้เปิดอยู่แล้ว ไม่ต้องสร้างซ้ำ',true);return;}const {error}=await supabaseClient.from('attendance_sessions').insert({session_code:code(sessionDate),subject_code:subjectCode,subject_name:subjectName,class_name:className,session_date:sessionDate,start_time:startTime,end_time:endTime,status:'open'});if(error){msg('สร้างคาบไม่สำเร็จ: '+error.message,true);return;}msg('เปิดคาบพิเศษสำเร็จ');form.reset();document.getElementById('sessionDate').value=localDate();await load();});
window.closeSession=async function(encoded){const id=decodeURIComponent(encoded),s=(sessions||[]).find(x=>String(x.id)===id);if(!s||s.status!=='open')return;if(!confirm('ต้องการปิดคาบนี้ใช่หรือไม่?'))return;const {error}=await supabaseClient.from('attendance_sessions').update({status:'closed'}).eq('id',id);if(error){msg('ปิดคาบไม่สำเร็จ: '+error.message,true);return;}msg('ปิดคาบเรียนแล้ว');await load();};
search.addEventListener('input',render);document.getElementById('sessionDate').value=localDate();load();
