const params=new URLSearchParams(location.search),sessionId=params.get('session');const info=document.getElementById('sessionInfo'),list=document.getElementById('studentList'),totalEl=document.getElementById('total'),presentEl=document.getElementById('present'),remainingEl=document.getElementById('remaining'),bar=document.getElementById('progressBar'),updated=document.getElementById('lastUpdated'),closeBtn=document.getElementById('closeBtn'),qrLink=document.getElementById('qrLink'),message=document.getElementById('message');let session=null;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function show(t,error=false){message.textContent=t;message.classList.remove('hidden');message.style.background=error?'#fee2e2':'#dcfce7';message.style.color=error?'#991b1b':'#166534';}
function statusLabel(v){return v==='present'?'🟢 มา':v==='late'?'🟡 สาย':v==='leave'?'🔵 ลา':v==='absent'?'🔴 ขาด':'⚪ ยังไม่เช็ก';}
async function loadSession(){if(!sessionId){show('ไม่พบ Session',true);return false;}const {data,error}=await supabaseClient.from('attendance_sessions').select('*').eq('id',sessionId).single();if(error){show('โหลด Session ไม่สำเร็จ: '+error.message,true);return false;}session=data;const open=session.status==='open';info.innerHTML=`<h2>${esc(session.subject_name)}</h2><p>${esc(session.subject_code)} • 👥 ${esc(session.class_name)}</p><p>📅 ${esc(session.session_date)} • ⏰ ${esc(session.start_time)}–${esc(session.end_time)}</p><p>Session: <strong>${esc(session.session_code)}</strong> • ${open?'🟢 เปิดรับเช็กชื่อ':'⚫ ปิดแล้ว'}</p>`;qrLink.href=`session-qr-v2.html?session=${encodeURIComponent(session.id)}`;qrLink.textContent=open?'📱 QR เช็กชื่อ':'🔒 QR ปิดแล้ว';closeBtn.disabled=!open;closeBtn.textContent=open?'🔒 ปิดการเช็กชื่อ':'🔒 ปิดแล้ว';return true;}
async function refresh(){if(!session)return;const {data:students,error:studentError}=await supabaseClient.from('attendance_students').select('id,student_id,prefix,first_name,last_name,class_name,status').eq('class_name',session.class_name).eq('status','active').order('student_id');if(studentError){show('โหลดรายชื่อนักเรียนไม่สำเร็จ: '+studentError.message,true);return;}const {data:records,error:recordError}=await supabaseClient.from('attendance_records').select('id,student_id,status,checked_at').eq('session_id',session.id);if(recordError){show('โหลดข้อมูลการเช็กชื่อไม่สำเร็จ: '+recordError.message,true);return;}const byStudent=new Map((records||[]).map(r=>[r.student_id,r]));const counts={present:0,late:0,leave:0,absent:0};(records||[]).forEach(r=>{if(counts[r.status]!==undefined)counts[r.status]++;});const open=session.status==='open';totalEl.textContent=students.length;presentEl.textContent=counts.present;remainingEl.textContent=Math.max(0,students.length-(records||[]).length);bar.style.width=students.length?`${Math.round(counts.present/students.length*100)}%`:'0%';list.innerHTML=(students||[]).map((s,i)=>{const r=byStudent.get(s.id);const name=[s.prefix,s.first_name,s.last_name].filter(Boolean).join(' ');const actions=open?(r?`<button type="button" class="small-button" onclick="changeStatus('${r.id}','present')">🟢</button><button type="button" class="small-button" onclick="changeStatus('${r.id}','late')">🟡</button><button type="button" class="small-button" onclick="changeStatus('${r.id}','leave')">🔵</button><button type="button" class="small-button" onclick="changeStatus('${r.id}','absent')">🔴</button>`:`<button type="button" class="small-button" onclick="markAbsent('${s.id}')">🔴 ขาด</button>`):'<span>🔒 ปิดการแก้ไข</span>';return `<div class="student-row"><span class="student-number">${i+1}</span><div class="student-name"><strong>${esc(name)}</strong><small>${esc(s.student_id)}</small></div><div class="student-state ${r?'present':'waiting'}">${r?statusLabel(r.status):'⚪ ยังไม่เช็ก'}${r&&r.checked_at?`<small>${new Date(r.checked_at).toLocaleTimeString('th-TH')}</small>`:''}<div class="status-actions">${actions}</div></div></div>`;}).join('');updated.textContent='อัปเดตล่าสุด '+new Date().toLocaleTimeString('th-TH');}
window.changeStatus=async function(recordId,status){if(!session||session.status!=='open'){show('คาบนี้ปิดแล้ว ไม่สามารถแก้สถานะได้',true);return;}const {error}=await supabaseClient.from('attendance_records').update({status}).eq('id',recordId);if(error){show('เปลี่ยนสถานะไม่สำเร็จ: '+error.message,true);return;}await refresh();};
window.markAbsent=async function(studentId){if(!session||session.status!=='open'){show('คาบนี้ปิดแล้ว ไม่สามารถบันทึกได้',true);return;}const {error}=await supabaseClient.from('attendance_records').insert({session_id:session.id,student_id:studentId,status:'absent'});if(error){if(error.code==='23505')show('นักเรียนคนนี้มีบันทึกอยู่แล้ว',true);else show('บันทึกขาดไม่สำเร็จ: '+error.message,true);return;}await refresh();};
closeBtn.addEventListener('click',async()=>{if(!session||session.status!=='open')return;if(!confirm('ปิดการเช็กชื่อคาบนี้หรือไม่? นักเรียนจะเช็กเพิ่มไม่ได้'))return;closeBtn.disabled=true;const {error}=await supabaseClient.from('attendance_sessions').update({status:'closed'}).eq('id',session.id);if(error){show('ปิด Session ไม่สำเร็จ: '+error.message,true);closeBtn.disabled=false;return;}await loadSession();await refresh();});
async function start(){if(await loadSession()){await refresh();setInterval(refresh,4000);setInterval(loadSession,10000);}}start();
