const form=document.getElementById('subjectForm'),codeInput=document.getElementById('subjectCode'),nameInput=document.getElementById('subjectName'),editId=document.getElementById('editId'),table=document.getElementById('subjectTable'),search=document.getElementById('searchSubject'),count=document.getElementById('subjectCount'),empty=document.getElementById('emptyState'),save=document.getElementById('saveSubject'),cancel=document.getElementById('cancelEdit'),connection=document.getElementById('connectionStatus'),message=document.getElementById('message');
let subjects=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function show(t,e=false){message.textContent=t;message.classList.remove('hidden');message.style.background=e?'#fee2e2':'#dcfce7';message.style.color=e?'#991b1b':'#166534';}
async function load(){const {data,error}=await supabaseClient.from('attendance_subjects').select('id,subject_code,subject_name,active').order('subject_code');if(error){connection.textContent='❌ เชื่อมต่อไม่ได้: '+error.message;connection.style.background='#fee2e2';connection.style.color='#991b1b';return;}subjects=data||[];connection.textContent='🟢 เชื่อมต่อฐานข้อมูลสำเร็จ';connection.style.background='#dcfce7';connection.style.color='#166534';render();}
function render(){const q=search.value.trim().toLowerCase(),rows=subjects.filter(s=>[s.subject_code,s.subject_name].some(v=>String(v??'').toLowerCase().includes(q)));count.textContent=`${subjects.length} วิชา`;empty.classList.toggle('hidden',rows.length>0);table.innerHTML=rows.map((s,i)=>`<tr><td>${i+1}</td><td><strong>${esc(s.subject_code)}</strong></td><td>${esc(s.subject_name)}</td><td>${s.active?'🟢 ใช้งาน':'⚪ ปิด'}</td><td class="actions"><button class="small-button" onclick="editSubject('${encodeURIComponent(s.id)}')">แก้ไข</button><button class="small-button" onclick="toggleSubject('${encodeURIComponent(s.id)}',${!s.active})">${s.active?'ปิด':'เปิด'}</button></td></tr>`).join('');}
form.addEventListener('submit',async e=>{e.preventDefault();const subject_code=codeInput.value.trim(),subject_name=nameInput.value.trim();if(!subject_code||!subject_name)return;save.disabled=true;try{let result;if(editId.value)result=await supabaseClient.from('attendance_subjects').update({subject_code,subject_name}).eq('id',editId.value);else result=await supabaseClient.from('attendance_subjects').insert({subject_code,subject_name,active:true});if(result.error)throw result.error;show(editId.value?'แก้ไขรายวิชาสำเร็จ':'เพิ่มรายวิชาสำเร็จ');reset();await load();}catch(e){show('บันทึกไม่ได้: '+e.message,true);}finally{save.disabled=false;}});
window.editSubject=function(encoded){const id=decodeURIComponent(encoded),s=subjects.find(x=>String(x.id)===id);if(!s)return;editId.value=s.id;codeInput.value=s.subject_code;nameInput.value=s.subject_name;save.textContent='💾 บันทึกการแก้ไข';cancel.classList.remove('hidden');codeInput.focus();};
window.toggleSubject=async function(encoded,active){const id=decodeURIComponent(encoded),s=subjects.find(x=>String(x.id)===id);if(!s)return;if(!active&&!confirm(`ปิดรายวิชา ${s.subject_code} หรือไม่? รายวิชาจะไม่ปรากฏในตารางใหม่`))return;const {error}=await supabaseClient.from('attendance_subjects').update({active}).eq('id',id);if(error){show('เปลี่ยนสถานะไม่ได้: '+error.message,true);return;}show(active?'เปิดรายวิชาแล้ว':'ปิดรายวิชาแล้ว');await load();};
function reset(){form.reset();editId.value='';save.textContent='➕ เพิ่มรายวิชา';cancel.classList.add('hidden');}cancel.addEventListener('click',reset);search.addEventListener('input',render);load();
